import { DataModel } from "../models/data.model";

// Extract from imdb
export const DataBase: DataModel[] = [
  new DataModel(1, "She Made Them Do It"),
  new DataModel(2, "Poka stanitsa spit"),
  new DataModel(3, "Memory Lane"),
  new DataModel(4, "No Through Road"),
  new DataModel(5, "Malcolm & Eddie"),
  new DataModel(6, "Violet"),
  new DataModel(7, "Last Call with Carson Daly"),
  new DataModel(8, "The Yellow Badge of Courage"),
  new DataModel(9, "Doctor Who: The Companion Chronicles"),
  new DataModel(10, "The Feed"),
  new DataModel(11, "Emmerdale Farm"),
  new DataModel(12, "The Jeselnik Offensive"),
  new DataModel(13, "Zero Minute"),
  new DataModel(14, "Nina and the Neurons Go Inventing"),
  new DataModel(15, "Dynamo"),
  new DataModel(16, "Ammattimies"),
  new DataModel(17, "Happening Now"),
  new DataModel(18, "The O'Reilly Factor"),
  new DataModel(19, "How Do I Look?"),
  new DataModel(20, "Electric Playground"),
  new DataModel(21, "Commissaire Laviolette"),
  new DataModel(22, "The Young Doctors"),
  new DataModel(23, "Married with Children"),
  new DataModel(24, "Le clan Pasquier"),
  new DataModel(25, "The Gale Storm Show: Oh! Susanna"),
  new DataModel(26, "Serangoon Road"),
  new DataModel(27, "The Young Doctors"),
  new DataModel(28, "Family Matters"),
  new DataModel(29, "Motormouth"),
  new DataModel(30, "Antiques Roadshow"),
  new DataModel(31, "Wasak"),
  new DataModel(32, "Prime News"),
  new DataModel(33, "May bukas pa"),
  new DataModel(34, "The Hollywood Squares"),
  new DataModel(35, "Els matins a TV3"),
  new DataModel(36, "Your Favorite Story"),
  new DataModel(37, "Los desayunos de TVE"),
  new DataModel(38, "The Small House at Allington"),
  new DataModel(39, "Minute to Win It"),
  new DataModel(40, "El ministerio del tiempo"),
  new DataModel(41, "The Fabulous Picture Show"),
  new DataModel(42, "Black Jack"),
  new DataModel(43, "Cutting Edge"),
  new DataModel(44, "Judge Joe Brown"),
  new DataModel(45, "All Saints"),
  new DataModel(46, "Quincy M.E."),
  new DataModel(47, "Neighbours"),
  new DataModel(48, "Chistoserdechnoe priznanie"),
  new DataModel(49, "John Halifax, Gentleman"),
  new DataModel(50, "Paul Flynn"),
  new DataModel(51, "Texas Monthly Talks"),
  new DataModel(52, "David Copperfield"),
  new DataModel(53, "Obruchalnoe koltso"),
  new DataModel(54, "Rock Macabre"),
  new DataModel(55, "The Tonight Show Starring Johnny Carson"),
  new DataModel(56, "Daesh molodezh"),
  new DataModel(57, "Wicked Wicked Games"),
  new DataModel(58, "Music Fair"),
  new DataModel(59, "Flip My Food with Chef Jeff"),
  new DataModel(60, "Un hombre solo"),
  new DataModel(61, "My S Rostova"),
  new DataModel(62, "Zwei bei Kallwass"),
  new DataModel(63, "Last Call with Carson Daly"),
  new DataModel(64, "Jimmy Kimmel Live!"),
  new DataModel(65, "Plebs"),
  new DataModel(66, "Lonelygirl15"),
  new DataModel(67, "Plus belle la vie"),
  new DataModel(68, "Watch What Happens: Live"),
  new DataModel(69, "WRAL Murder Trials"),
  new DataModel(70, "Secrets of the Bible"),
  new DataModel(71, "Six O'Clock News"),
  new DataModel(72, "Jackie Gleason: American Scene Magazine"),
];