import { ProductModel } from "../models/product.model";

// Extract from imdb
export const ProductsBase: ProductModel[] = [
  new ProductModel(1, "She Made Them Do It", "", "Completed"),
  new ProductModel(2, "Poka stanitsa spit", "", "Completed"),
  new ProductModel(3, "Memory Lane", "", "Completed"),
  new ProductModel(4, "No Through Road", "", "Completed"),
  new ProductModel(5, "Malcolm & Eddie", "", "Completed"),
  new ProductModel(6, "Violet", "", "Completed"),
  new ProductModel(7, "Last Call with Carson Daly", "", "Completed"),
  new ProductModel(8, "The Yellow Badge of Courage", "", "Completed"),
  new ProductModel(9, "Doctor Who: The Companion Chronicles", "", "Completed"),
  new ProductModel(10, "The Feed", "", "Completed"),
  new ProductModel(11, "Emmerdale Farm", "", "Completed"),
  new ProductModel(12, "The Jeselnik Offensive", "", "Completed"),
  new ProductModel(13, "Zero Minute", "", "Completed"),
  new ProductModel(14, "Nina and the Neurons Go Inventing", "", "Completed"),
  new ProductModel(15, "Dynamo", "", "Completed"),
  new ProductModel(16, "Ammattimies", "", "Completed"),
  new ProductModel(17, "Happening Now", "", "Completed"),
  new ProductModel(18, "The O'Reilly Factor", "", "Completed"),
  new ProductModel(19, "How Do I Look?", "", "Completed"),
  new ProductModel(20, "Electric Playground", "", "Completed"),
  new ProductModel(21, "Commissaire Laviolette", "", "Completed"),
  new ProductModel(22, "The Young Doctors", "", "Completed"),
  new ProductModel(23, "Married with Children", "", "Completed"),
  new ProductModel(24, "Le clan Pasquier", "", "Completed"),
  new ProductModel(25, "The Gale Storm Show: Oh! Susanna", "", "Completed"),
  new ProductModel(26, "Serangoon Road", "", "Completed"),
  new ProductModel(27, "The Young Doctors", "", "Completed"),
  new ProductModel(28, "Family Matters", "", "Completed"),
  new ProductModel(29, "Motormouth", "", "Completed"),
  new ProductModel(30, "Antiques Roadshow", "", "Completed"),
  new ProductModel(31, "Wasak", "", "Completed"),
  new ProductModel(32, "Prime News", "", "Completed"),
  new ProductModel(33, "May bukas pa", "", "Completed"),
  new ProductModel(34, "The Hollywood Squares", "", "Completed"),
  new ProductModel(35, "Els matins a TV3", "", "Completed"),
  new ProductModel(36, "Your Favorite Story", "", "Completed"),
  new ProductModel(37, "Los desayunos de TVE", "", "Completed"),
  new ProductModel(38, "The Small House at Allington", "", "Completed"),
  new ProductModel(39, "Minute to Win It", "", "Completed"),
  new ProductModel(40, "El ministerio del tiempo", "", "Completed"),
  new ProductModel(41, "The Fabulous Picture Show", "", "Completed"),
  new ProductModel(42, "Black Jack", "", "Completed"),
  new ProductModel(43, "Cutting Edge", "", "Completed"),
  new ProductModel(44, "Judge Joe Brown", "", "Completed"),
  new ProductModel(45, "All Saints", "", "Completed"),
  new ProductModel(46, "Quincy M.E.", "", "Completed"),
  new ProductModel(47, "Neighbours", "", "Completed"),
  new ProductModel(48, "Chistoserdechnoe priznanie", "", "Completed"),
  new ProductModel(49, "John Halifax, Gentleman", "", "Completed"),
  new ProductModel(50, "Paul Flynn", "", "Completed"),
  new ProductModel(51, "Texas Monthly Talks", "", "Completed"),
  new ProductModel(52, "David Copperfield", "", "Completed"),
  new ProductModel(53, "Obruchalnoe koltso", "", "Completed"),
  new ProductModel(54, "Rock Macabre", "", "Completed"),
  new ProductModel(55, "The Tonight Show Starring Johnny Carson", "", "Completed"),
  new ProductModel(56, "Daesh molodezh", "", "Completed"),
  new ProductModel(57, "Wicked Wicked Games", "", "Completed"),
  new ProductModel(58, "Music Fair", "", "Completed"),
  new ProductModel(59, "Flip My Food with Chef Jeff", "", "Completed"),
  new ProductModel(60, "Un hombre solo", "", "Completed"),
  new ProductModel(61, "My S Rostova", "", "Completed"),
  new ProductModel(62, "Zwei bei Kallwass", "", "Completed"),
  new ProductModel(63, "Last Call with Carson Daly", "", "Completed"),
  new ProductModel(64, "Jimmy Kimmel Live!", "", "Completed"),
  new ProductModel(65, "Plebs", "", "Completed"),
  new ProductModel(66, "Lonelygirl15", "", "Completed"),
  new ProductModel(67, "Plus belle la vie", "", "Completed"),
  new ProductModel(68, "Watch What Happens: Live", "", "Completed"),
  new ProductModel(69, "WRAL Murder Trials", "", "Completed"),
  new ProductModel(70, "Secrets of the Bible", "", "Completed"),
  new ProductModel(71, "Six O'Clock News", "", "Completed"),
  new ProductModel(72, "Jackie Gleason: American Scene Magazine", "", "Completed"),
];